config/atmos_github_summary.yaml
=> corrected template typo

README.md, action.yml, config/atmos_github_summary.yaml, docs/github-action.md
- quality of life improvements for v0 release
- QoL improvements
- n/a
=> v0 Release Improvements

action.yml, config/atmos_github_summary.yaml
- Added support for infracost
- Added support for infracost
- https://www.infracost.io/
=> Added support for infracost

config/atmos_github_summary.yaml
- Create unique user-content id for each component + stack
- When running over a matrix, we need unique user-content links
- DEV-1055
=> Unique `user-content` IDs

action.yml
- Fixed version for plan storage step
- Step should point to release version and not to branch
=> Fixed version for plan storage step

action.yml
- added input to overwrite SHA
- added input to overwrite SHA
=> Overwrite sha

.github/workflows/test-changes-exists-drift.yml, .github/workflows/test-failed-plan-drift.yml, .github/workflows/test-no-changes-drift-more.yml, .github/workflows/test-settings-action-disabled-drift.yml, .github/workflows/test-settings-action-disabled.yml, action.yml, config/github_issue_description.yaml, stacks/catalog/foobar-disabled.yaml, stacks/orgs/foo/plat/sandbox/plat-ue2-sandbox.yaml
* Added failed plan test 
* Covered test case for a failed plan
=> Added failed test plan

.github/workflows/test-changes-exists-drift.yml, .github/workflows/test-changes-exists.yml, .github/workflows/test-infra-cost.yml, action.yml, config/atmos_github_summary.yaml, config/github_issue_description.yaml, stacks/catalog/foobar-changes.yaml
* Replace `/` with `-` in components names
* Fix summary file name
=> Added tests for component name spashes

.github/workflows/test-failed-plan-drift.yml, action.yml
=> Fix metadata upload

action.yml
* Use workdir instead of `cd` in bash
* To avoid side effects
=> Fix changedir

action.yml
* Fix atmos base path problem
* Relative path resolves wrong in `remote-state` component
=> Fix atmos base path problem

action.yml
* Added `ATMOS_BASE_PATH` variables
* Fix `remote-state` module usage
=> Added atmos yaml

.github/workflows/test-changes-exists-drift.yml, .github/workflows/test-changes-exists.yml, .github/workflows/test-infra-cost.yml, config/atmos_github_summary.yaml, config/github_issue_description.yaml
* Fix anchors
* Github added prefix `user-content-` for all links `id`
=> Fix anchors

.github/workflows/test-changes-exists-drift.yml, .github/workflows/test-changes-exists.yml, .github/workflows/test-failed-plan.yml, .github/workflows/test-infra-cost.yml, action.yml, config/summary.yaml
* Drift mode have step summary
* Required for https://github.com/cloudposse/github-action-atmos-terraform-drift-detection step
=> Drift mode have step summary

action.yml
=> Fix null char

.github/workflows/test-changes-exists-drift.yml, .github/workflows/test-changes-exists.yml, .github/workflows/test-failed-plan-drift.yml, .github/workflows/test-failed-plan.yml, .github/workflows/test-infra-cost.yml, config/summary.yaml
=> Improve fail markdown

.github/workflows/test-changes-exists-drift.yml, .github/workflows/test-no-changes-drift-more.yml, action.yml
* Create metadata.json even if there is drift or error in drift mode
* This behaviour expected by drift detection action
=> Fix drift detection mode

action.yml
* Fix atmos remote state 
* Cloudposse utils provider need absolute path to atmos config
=> Fix atmos remote state 

action.yml
* Install tfcmt to toolchain dir
* Old action `shmokmt/actions-setup-tfcmt@v2` installed `tfcmt` to global directory that lead to conflicts
=> Install tfcmt

.github/workflows/test-changes-exists-drift.yml, .github/workflows/test-changes-exists.yml, .github/workflows/test-failed-plan-drift.yml, .github/workflows/test-failed-plan.yml, .github/workflows/test-infra-cost.yml, .github/workflows/test-no-changes-drift-more.yml, .github/workflows/test-no-changes.yml, action.yml, tests/components/terraform/foobar/main.tf, tests/stacks/catalog/foobar-changes.yaml, tests/stacks/catalog/foobar-disabled.yaml, tests/stacks/catalog/foobar-fail.yaml, tests/stacks/catalog/foobar.yaml, tests/stacks/orgs/foo/plat/sandbox/plat-ue2-sandbox.yaml
* Show no changes summary in regular plan mode
* Plan workflow should display a summary for all stacks, even if there are no changes
* https://cloudposse.atlassian.net/browse/DEV-1164
=> Show no changes summary in regular plan mode

.github/workflows/test-changes-exists-drift.yml, .github/workflows/test-failed-plan-drift.yml, .github/workflows/test-no-changes-drift-more.yml, .github/workflows/test-no-changes.yml, .github/workflows/test-settings-action-disabled-drift.yml, .github/workflows/test-settings-action-disabled.yml, action.yml
* Artifact upload rollback v3
broke in #65
=> Artifact upload rollback v3

action.yml
* Atmos pro deployments status upload
* Integrate action with Atmos pro
=> Atmos pro deployments status upload

.github/workflows/test-atmos-pro-enabled.yml, .github/workflows/test-changes-exists-drift.yml, .github/workflows/test-changes-exists.yml, .github/workflows/test-failed-plan-drift.yml, .github/workflows/test-failed-plan.yml, .github/workflows/test-infra-cost.yml, .github/workflows/test-no-changes-drift-more.yml, .github/workflows/test-no-changes.yml, .github/workflows/test-settings-action-disabled-drift.yml, .github/workflows/test-settings-action-disabled.yml
- Remove `Makefile`
- Add `atmos.yaml`
- Replace `build-harness` with `atmos` for readme genration
* DEV-3229 Migrate from build-harness to atmos
=> Replace Makefile with atmos.yaml

.github/workflows/test-changes-exists.yml, action.yml
* Added TFCMT_GITHUB_TOKEN environment variable to the action.
* Provide permissions to publish PR comments 
* https://github.com/orgs/cloudposse/discussions/103%7C#103
=> Add TFCMT_GITHUB_TOKEN to action.yml
